export const TARGET_ASPECT = 9 / 16;
export const TRACK_SCROLL_SPEED = 55; // px per second
export const BASE_SCORE_GAIN = 60;
export const MAX_DISTANCE_RATIO = 0.45;
export const ACCURACY_THRESHOLD = 0.6;
export const DAMAGE_PER_SECOND = 40;
export const ENERGY_REGEN_PER_SECOND = 8;
export const PLAYER_VERTICAL_RATIO = 0.7;
export const PLAYER_RADIUS_RATIO = 0.018;
export const PLAYER_LERP_SPEED = 7;
export const BACKGROUND_COLOR = '#060713';
export const TRACK_LINE_COLOR = '#39ffe0';
export const TRACK_LINE_WIDTH = 3;
export const PLAYER_COLOR = '#ffd952';
export const HUD_TEXT_COLOR = '#f2f5ff';
export const ENERGY_BAR_BG = 'rgba(255, 255, 255, 0.15)';
export const ENERGY_BAR_FILL = '#ff3c82';
export const OVERLAY_BG = 'rgba(0, 0, 0, 0.55)';
